language: python

python:
  - 3.6

#services: mariadb

install:
  - pip install -r requirements.txt

#before_script:
#  - mysql -e 'create database test;' -u root

script: 
  - python manage.py test

